- hosts: all
  become: yes
  tasks:
    - name: Install HAProxy
      apt:
        name: haproxy
        state: present
        update_cache: yes

    - name: Ensure HAProxy is enabled and running
      service:
        name: haproxy
        state: started

    - name: Parse frontends
      set_fact:
        frontends_dict: "{{ frontends | from_json }}"
        backends_dict: "{{ backends | from_json }}"

    - name: Generate HAProxy configuration from template
      template:
        src: haproxy.cfg.j2
        dest: /tmp/haproxy.cfg
        # dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0644
      vars:
        frontends: "{{ frontends_dict }}"
        backends: "{{ backends_dict }}"
      notify: Restart HAProxy

    # - name: Copy HAProxy config
    #   copy:
    #     src: ./haproxy.cfg
    #     dest: /etc/haproxy/haproxy.cfg
    #     owner: root
    #     group: root
    #     mode: 0644
    #   notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted
